// DO NOT EDIT THIS FILE
// This is an example data from your Grocery shopping trip to Hack Reactor Whole Food's Joes
// window.exampleVideoData = [
//   {id: 1, quantity: 5, description: "frozen pizza"},
//   {id: 2, quantity: 10, description: "greek yogurt"},
//   {id: 3, quantity: 2, description: "wine"},
//   {id: 4, quantity: 1, description: "iced coffee"}
// ];

var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/groceries');

var grocerySchema = mongoose.Schema({
  description: String,
  quantity: Number
});

var Item = mongoose.model('Item', grocerySchema);

var save = (item) => {
  console.log(' i ran inside db');
  var entry = new Item({
    description: item.description,
    quantity: item.quantity
  });
  entry.save(function(err, entry) {
    if (err) {
      console.log('did not save to db');
    } else {
      console.log('saved to db');
    }
  });
}

var fetch = (callback) => {
  Item.find(function(err, items) {
    if(err) {
      return console.log('unable to find');
    } else {
      callback(items);
    }
  })
}

module.exports.save = save;
module.exports.fetch = fetch;





